### PR TITLE
Updated for Rust 1.0

### PR DESCRIPTION
**Pull request by dyule**
If you're still interested in working on this, I've brought it up to date with Rust as it currently stands, and you can merge the changes in.  If you're not, I'll keep working on it on my fork.  My goal is to create a embeddable library for Python.

### CODE REVIEW

**Comment by jjacobson93** [comment]
I don't have much time to spend on this project. In the mean time, I will merge your pull request and add you as a collaborator.

**Comment by jjacobson93** [comment]
Just cloned your repo. Looks like the tests are running and it works, but the shell is a little wonky with the `print!` macro it seems. Let me know if you're having the same issue.

**Comment by dyule** [comment]
Yeah, for some reason the print command is running after reading the input.  I'm not sure why that's the case, since from what I can tell that's not how it's written.  I changed very little in the shell file, so I don't know why it might suddenly be doing that, but it has been since I got it to compile.

**Comment by jjacobson93** [comment]
Looks like stdout needs to be flushed: https://doc.rust-lang.org/std/macro.print!.html

Here's an example. Without the flush calls, it will print after reading the input.

``` rust
use std::io::{self, BufRead, Write};

fn main() {
    println!("1");
    println!("2");

    print!(">>> ");

    io::stdout().flush().unwrap();

    let locked_in = io::stdin();
    for line in locked_in.lock().lines() {
        match line {
            Ok(s) => {
                println!("{}", s);
                print!(">>> ");
                io::stdout().flush().unwrap();
            },
            Err(e) => panic!("Error: {}", e)
        }
    }
}
```

**Comment by dyule** [comment]
I've fixed the flushing problem.  I thought that might be it, but I hadn't spent the time to dig through the docs

**Comment by jjacobson93** [comment]
Looks good. Merging.

**Pull request merged**
